
version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=bankmore
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  contacorrente.api:
    image: ${DOCKER_REGISTRY-}contacorrenteapi
    build:
      context: .
      dockerfile: BankMore.API.ContaCorrente/Dockerfile
    ports:
      - "5074:8080"
    environment:
      - ConnectionString=Host=postgres;Port=5432;Database=bankmore;Username=user;Password=password
      - JWT_KEY=bankmore-secure-jwt-key-for-production
    depends_on:
      - postgres

  transferencia.api:
    image: ${DOCKER_REGISTRY-}transferenciaapi
    build:
      context: .
      dockerfile: BankMore.API.Transferencia/Dockerfile
    ports:
      - "5237:8080"
    environment:
      - ConnectionString=Host=postgres;Port=5432;Database=bankmore;Username=user;Password=password
      - JWT_KEY=bankmore-secure-jwt-key-for-production
    depends_on:
      - postgres
      - contacorrente.api

  

volumes:
  postgres_data:

